### ISSUE TITLE
ConfigOptions mehrfach

### ISSUE THREAD

**Issue by jonashauff** [maltehol/angular-cypress-graphql-mock#8]
Wenn ich die cypress-Version auf 4.9.0 aktualisiere und die Tests headless ausführen lassen will, dann erscheint der Fehler  "Duplicate identifier 'ConfigOptions'." Ändere ich den Namen von ConfigOptions im angegebenem Pfad, dann laufen die Tests ohne Probleme durch.
![Unbenannt](https://user-images.githubusercontent.com/54169769/85523818-be2f0400-b607-11ea-9e1d-717ffa1fd05a.PNG)

**Comment by maltehol** [comment]
Behoben mit Version 0.4.0
